# -*- coding: utf-8 -*-
"""prompt engineering workbook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTjl3-EFmERLo8CyehpEyVrPGFLiwS6x
"""

!pip install google-generativeai
!pip install datasets

import warnings
warnings.filterwarnings('ignore')

import google.generativeai as genai
from google.colab import userdata

api_key = userdata.get('GEMINI_API_KEY')
genai.configure(api_key=api_key)

model = genai.GenerativeModel('gemini-2.5-pro')

"""### Basic Promts

The delimiters are given to llms to understand some specific instruction

1. ''' - the quotes
2. <> Angles
3. .## Hash usually double
4. ''' double quotes
5. <> </> - aml tags
6. -- 2 dash
7. ** double star
"""

prompt = '''
Please explain linear regression

'''
output = model.generate_content(prompt).text
print(f'the prompt output is : {output}')

"""## structure the prompt"""

prompt = '''
<role> you are expert in machine learning.
<goal> please explain linear regression.
<context> the learner is very fresh to the field of data science.
<instruction> keep the explanation simple, short and precise.
<format> provide the responses in bullet numbered format.
<style> Be encouraging in your responses and positive.
'''
output = model.generate_content(prompt).text
print(f'the prompt output is : {output}')

"""#### code"""

prompt = '''
<role> you are expert code python developer.
<goal> write a code for linear regression model.
<context> learner is aware of EDA.
<instruction> keep the explanation simple, short and precise. explain missing values,if any, scalling and transformatin if required \n
also implement best practices followed in the industry.
<format> please do put up comments where ever required.
'''
output = model.generate_content(prompt).text
print(f'the prompt output is : {output}')

"""## Creative Writing"""

prompt = '''
<role> you are expert in english literature.
<goal> write a poem on Genrative AI.
<context> start from what is basics of GenAi and also llms.
<instruction> keep the explanation simple, short and precise. poem should be in maximum in 50 lines
<format> display in stanzas
<style> Be romantic, playfull and joyous.
'''
output = model.generate_content(prompt).text
print(f'the prompt output is : {output}')

"""## medical domain"""

prompt = '''
<role> you are a medicall expert in diagonizing cancer diseases.
<goal> please explain how AI is revolutionalizing in detecting cancer.
<context> there are many people in the world infected by cancer and need imediate attention.
<instruction> Avoid using medical jargons and explain as if you are explaining to beginner, keep 100 lines.
<format> start with introduction and summerize them into three paragraphs. the first paragraph is introduction, second is its impact\n
third is future of AI development.
<style> Be professional, optimistic and informative.
'''
output = model.generate_content(prompt).text
print(f'the prompt output is : {output}')

"""### Dietician"""

prompt = '''
### role: you are expert certified dietician.
### goal: create a weekly vegeterian diet plan for a adult of 50 years.
### context: the adult has type 2 diabetes.
### instruction: focus on low fats, high calories and low carbs and avoid sugar and sufficint protiens
### format: day wise tabular format plan. that has breakfast, lunch dinner.
### style: Be cultually sensitive.
'''
output = model.generate_content(prompt).text
print(f'the prompt output is : {output}')

prompt = '''
<role> you are a gym expert.
<goal> please explain how i can get more weight.
<context> i want 3 more kg wieght in next one month
<instruction> tell me how long should i exerices and make a diet plan for me to get more weight.
<format> give everything in simple way
<style> Be professional, couragious.
'''
output = model.generate_content(prompt).text
print(f'the prompt output is : {output}')

"""ZERO SHOT Prompting

1. these are the basics prompting techniques which completly rely on the
capability of LLMs.
2. no examples are provided in zero shot prompting.
3. Direct instruction are given to the model to perform the task.
4. LLM are trained on large valume of data and the outputs of LLM's are based on the training that models have undergone.
"""

zero_short = '''please explain principal component analysis which is part of unsupervised learning.
'''
output = model.generate_content(zero_short).text
print(f'the prompt output is : {output}')

"""Text Classification"""

zero_prompt = '''
## you are and expert in classifying the text
## you are required to classify the text into positive, negative and neutral.

I must say it has exceded my expectations. the build quality is exceptional with a study design that feels premium and durable.
the key are well spaced and provid a comfortable typing experience even during prolonged use.

## please give reason for classification.
## keep it simple and let me know if we can go for the product.
## the output should be in bullated format numbered as (eg 1. 2. 3.)
'''
output = model.generate_content(zero_prompt).text
print(f'the prompt output is : {output}')

"""## job evaluation and fitness of job"""

job_desc = '''
• Strong understanding of ML fundamentals, Transformers, embeddings, and LLM architecture
• Hands-on experience with HuggingFace, PyTorch, TensorFlow, LangChain, or similar tools
• Experience working on academic/side projects involving model training or fine-tuning
• Ability to experiment, test, validate, and iterate on model behavior
• Passion for applied AI and improving real-world model performance
'''
print(job_desc)

!pip install -q pypdf

from pypdf import PdfReader
resume = PdfReader('/content/Anand_AI.pdf')
resume.text = ''
for page in resume.pages:
  resume.text += page.extract_text()

prompt = f'compare the \n\n{job_desc} with \n\n{resume.text} and suggest if i am a good fit? and give me the ATS score after camparing with jd'
response = model.generate_content(prompt)
print(response.text)

job_desc = '''Basic understanding of AI/ML concepts (e.g., LLMs, NLP, neural networks).
Hands-on experience with ChatGPT or similar AI tools.
Strong interest in Generative AI, automation, and prompt engineering.
Basic Python knowledge.
Ability to research, learn, and experiment quickly.
Good communication and documentation skills.
Problem-solving mindset with attention to detail.
Familiarity with AI tools like Midjourney, Claude, HuggingFace, or Google AI is a plus.
Ability to work independently and manage tasks responsibly.
'''
print(job_desc)

"""Few short  prompting"""

from pypdf import PdfReader
resume = PdfReader('/content/Anand_AI.pdf')
resume.text = ''
for page in resume.pages:
  resume.text += page.extract_text()

prompt = f'compare the \n\n{job_desc} with \n\n{resume.text} and suggest if i am a good fit? and give me the ATS score after camparing with jd'
response = model.generate_content(prompt)
print(response.text)

few_short = '''
provide a solution to the mathematical problem
stated below. Give the final output only
Q: 4X + 8 = 0 then X is
A: -2

Q: 5X + 2Y = 8 when X=0 is Y = 4
A: 4
Q: 5X + 2Y = 8 when X=2 is Y is
A: 3
Q: 3X*2 + Y = 0 when X= 4 then Y is
A:
'''
output = model.generate_content(few_short).text
print(f'the prompt output is :{output}')

few_shot = '''
find the data when the module should have been conducted

example 1:
input: python for data science course was to start on 12th oct 2024. this takes 5 days to complete. it got delayed by 10 days.
conclusion: so the python for data science course started actually on 22nd oct 2024

example2:
input: the next course that was to start was eda. it was a start on 10th nov 2024. it is a 5 day course. the faculy
was readily available and hence the course was preponed by 5 days.
conclusion: so the eda course started actually on 5th nov 2024.

example3:
input: statistics course was to start on 17th nov 2024. statistics is 5 day course. it was decided to preponse this course by 3 days.
conclusion: so the statistics course started actually on 20th nov 2024.
'''
output = model.generate_content(few_shot).text
print(f'the prompt output is :{output}')

examples = [ {
    'input': 'i am learning generative  AI',
    'output': 'estoy apprendiendo AI generative'
    }, {
    'input': 'life is good after learning AI',
    'output': 'livet er godt effer at have laert AI'
}]
prompt = 'tranaslate the following into hindi. i hate to go to study these days'
response = model.generate_content(prompt+'\n\n{examples}\n\n'+str(examples))
print(response.text)

"""### Coding example"""

examples_text = """
example 1:
input: get all the employees from the employees table
output: select * from employees

example 2:
input: find employees with salary greater than 25000
output: select * from employees where salary > 25000
"""

prompt = f"""{examples_text}

write a sql query to get the 2nd highest salary of the employees
output:
"""
response = model.generate_content(prompt)
print(response.text)

"""## Chain of Thoughts

1. in chain of thoughts, we give LLM a step by step process to describe the reasoning logic.
2. so we create logical chain of reasoning to arrive at the solution or the response.
3. step by step process inducing the thought into the LLMs which refines the explanation provided by the LLMs.
4. It brings in improved clarity and even the complex problem can be well explained in simpler way.
5. the accuracy tends to increasse by structuring the thought process
6. step by step process also ensures that the logical sequences are followed.

# the ambiguity of life career
"""

# epic problem: Pursue masters from USA or continue with the job in India
thought = 'Question-Act As a career expert in the field of AI and answer the following question. Do i continue my job in india that  paying me descent money or shall i go to USA to pursue my masters from IVy league colleges such MIT and standford etc.'

'''
evaluate the options:
1. asses the current situation: i have recently gotten into job as data scientist and quite content my role. I am doing \
something serious to uplift my carrer. howeever, the seniour in my company have gone abroad to pursue higher studies.\
this gets me into the thought of pursuing higher studies.

2. if i leave the job : if i have to leave the job then i have to leave my family behind and at the same time there is an \
opportunity cost involved. what that also means is, if i am out of job, i will loose on the salary that i was getting.\
this is one of the issues that is not let me decide.

3. financial situation: i understand pursuing master from abroad is very costly and can cost me heavily. it might\
take couple of years to come out my education loan. howeever, i feel it is worth doing it once in life time opportunity\
moreever i do not have financial constrains.

now i want you to guide me using logical reasoning and suggest me the correct options providing weightage to all the options\
that you suggest.

Note: the optiones that you provide shoud be practical and can be enacted.
'''
response = model.generate_content(thought)
print(response.text)

thought = '''
you are an expert in virtual tour for the past 72 years in india. you have people coming from all parts of the world in delhibegin your itinary  step by step.

1. give all the important location in and arund Delhi.
2. give the reason why these monuments where built and who had built these.
3. How long did it take to construct these monuments.
4. when did it start and when did it end.
5. also mentioin the number of people who visit these monuments through the year.

can you also make it appear romantic and joyful so that the reader gets interest to read this itinary.

'''
response = model.generate_content(thought)
print(response.text)

# Math and Logical Thinking
thought = '''
You are an expert in the field of mathematics and logical reasoning.
we are required to solve a complex problemm which is in power of 2 (quadratic equation)
lets take an example and then divide this into step by step process

X**2 + 2XY + Y**2 = 0
step 1: split them into component of x and y
step 2: look for the common factors. think in such a way that you put this in the form of formula like (X+Y)**2
step 3: now equate this to = 0 and solve for x and y
step 4: provide the values of x and y.
solve this complex equation
2X**2 + 10XY + 4Y**2 = 0

'''
response = model.generate_content(thought)
print(response.text)

"""## Tree of thoughts

"""

!pip install -q langchain-google-genai
!pip install -q langchain

!pip install --upgrade google-generativeai langchain_google_genai

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage

import langchain
import langchain_core
import langchain_google_genai

print(langchain.__version__)

!pip install langchain>=0.3.0 langchain-google-genai

from langchain_core.globals import set_llm_cache
set_llm_cache(None)

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage

model = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash",
    api_key=api_key,
)

response = model.invoke([
    HumanMessage(content="explain tree of thoughts with example")
])

print(response.content)

#multiple job offers in hand
prompt = '''
I have 3 jobs and need to decide one to take. help me think through this systematically
by exploring ways to evaluate.
job A: Big tech company , 7 lakhs/annum, long hours, great benefits
job B: start up 6 lakhs/annum, flexible hours, equity options, uncertain future
job C: local company, 6.5 lakhs/annum, good work-life balance, limited growth
think about this from multiple view points and help me decide
what i want to explore:
view point1: financial comarision(salary, benefit, long-term earning potential)
view point2: career growth opportunities
view point3: work-life balance and personal happiness
view point4: risk vs stability
final synthesis: whicj job best matched my priorties
'''
response = model.invoke([HumanMessage(content = prompt)])
print(response.content)

prompt = '''
i have exam in 3 weeks and need a stydy plan. please explore different ways to organize my study time and recommand the best approach.
exam:
-python for data science (easiest for me, scored 90% in previos exam)
-statistics (hardest for me, scored 60% in previous exam)
-machine learning 1(easiest for me, scored 80% in previous exam)
-unsupervised learning(medium difficult, socred 72% in previous exam)
consider different studies stratagies and tell me which would work the best.

 i want you to explore different stratagies as listed below.

 stratedy1: study hardest subject first
 stratedy2: study easiest subject first
 stratedy3: study medium difficult

 evaluation: which strategy fits my learning style and maximizes my grades?.
 '''
response = model.invoke([HumanMessage(content = prompt)])
print(response.content)

"""### Self consistency

"""

prompt = '''
i want to solve a math problem in 3 diferent ways to check for consistency.
problem: what is 15% of 240?
method 1: [solve using percentage formula]
method 2: [solve using decimal conversion]
method 3: [solve using fraction approach]
campare your answer- do they all match
'''
response = model.invoke([HumanMessage(content = prompt)])
print(response.content)

"""### reasoning problems"""

prompt = '''
I want to analyze this logic problem from 3 different angles to ensure consistency:
problem: if all roses are flowers and some flowers are red, can we conclude that some roses are red?
analysis1: use formal logic rules
analysis2: use everyday reasoning
analysis3: use examples to test the conclusion
do all the three approaches give me the same results?
'''
response = model.invoke([HumanMessage(content = prompt)])
print(response.content)

"""### Loading Images- Images to Text"""

!pip install transformers

from PIL import Image

import google.generativeai as genai
from google.colab import userdata
api_key = userdata.get('GEMINI_API_KEY')
genai.configure(api_key=api_key)

!pip install google-generativeai pillow

from PIL import Image as PILImage # Alias PIL.Image to avoid name conflict

def generate_image_caption(image_path):
  if image_path:
    # Use PILImage.open() to open the image
    image = PILImage.open(image_path)
    model = genai.GenerativeModel('gemini-2.5-flash')
    response = model.generate_content(['Describe this image in details', image])
    return response.text
  else:
    return 'No Image proved'
image_path = '/content/DOG.jpg'
caption = generate_image_caption(image_path)
print(caption)



for m in genai.list_models():
  print(f'{m.name}: {m.supported_generation_methods}')

"""### Model evaluation Benchmarks

# Benchmark for text
# BLEU: Bilingual evaluation understudy

## Rogue
#### recall oriented understudy for gisting evaluation
"""

